version: '2'

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gosec
    - godox
    - ireturn
    - mnd
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    funlen:
      # Complexity is already covered by gocognit.
      statements: -1
    govet:
      enable-all: true
      disable: [fieldalignment]
    nolintlint:
      require-specific: true
  exclusions:
    presets:
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gocognit
          - goconst
          - gocritic
        path: (.+)_test.go
      - linters: [govet]
        text: 'shadow: declaration of "err" shadows declaration'
      - linters: [goconst]
        source: 'fs\.PathError'
    paths:
      - testdata

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    gofumpt:
      extra-rules: true
    golines:
      max-len: 120
      tab-len: 1
